model1_GroundTruth=["{'Criminal Planning/Confessions': 0,\n",
              " 'Safe': 1,\n",
              " 'Profanity': 2,\n",
              " 'Hate/Identity Hate': 3,\n",
              " 'Violence': 4,\n",
              " 'PII/Privacy': 5,\n",
              " 'Needs Caution': 6,\n",
              " 'Sexual, Violence': 7,\n",
              " 'Controlled/Regulated Substances, Criminal Planning/Confessions, PII/Privacy': 8,\n",
              " 'Controlled/Regulated Substances, Suicide and Self Harm': 9,\n",
              " 'Harassment, PII/Privacy': 10,\n",
              " 'Sexual (minor)': 11,\n",
              " 'Guns and Illegal Weapons, Violence': 12,\n",
              " 'Guns and Illegal Weapons': 13,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons, Hate/Identity Hate': 14,\n",
              " 'Controlled/Regulated Substances, Threat, Violence': 15,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons, Violence': 16,\n",
              " 'Controlled/Regulated Substances': 17,\n",
              " 'Sexual': 18,\n",
              " 'Criminal Planning/Confessions, Sexual': 19,\n",
              " 'Harassment, Sexual, Violence': 20,\n",
              " 'Harassment, Hate/Identity Hate': 21,\n",
              " 'Other': 22,\n",
              " 'Harassment, Profanity': 23,\n",
              " 'Harassment': 24,\n",
              " 'Harassment, PII/Privacy, Profanity, Violence': 25,\n",
              " 'Suicide and Self Harm': 26,\n",
              " 'Criminal Planning/Confessions, Hate/Identity Hate, Violence': 27,\n",
              " 'Criminal Planning/Confessions, Profanity': 28,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons': 29,\n",
              " 'Controlled/Regulated Substances, Criminal Planning/Confessions': 30,\n",
              " 'Harassment, Hate/Identity Hate, Profanity': 31,\n",
              " 'Hate/Identity Hate, Violence': 32,\n",
              " 'Criminal Planning/Confessions, Violence': 33,\n",
              " 'Sexual, Sexual (minor)': 34,\n",
              " 'Guns and Illegal Weapons, Hate/Identity Hate, Violence': 35,\n",
              " 'Harassment, Hate/Identity Hate, PII/Privacy': 36,\n",
              " 'Criminal Planning/Confessions, PII/Privacy': 37,\n",
              " 'Guns and Illegal Weapons, Suicide and Self Harm': 38,\n",
              " 'Controlled/Regulated Substances, Criminal Planning/Confessions, Sexual': 39,\n",
              " 'Profanity, Violence': 40,\n",
              " 'Harassment, Sexual': 41,\n",
              " 'Hate/Identity Hate, Profanity': 42,\n",
              " 'Profanity, Sexual': 43,\n",
              " 'Criminal Planning/Confessions, Sexual, Violence': 44,\n",
              " 'Threat, Violence': 45,\n",
              " 'Threat': 46,\n",
              " 'Harassment, PII/Privacy, Violence': 47,\n",
              " 'Hate/Identity Hate, Sexual, Violence': 48,\n",
              " 'Criminal Planning/Confessions, Suicide and Self Harm, Violence': 49,\n",
              " 'Criminal Planning/Confessions, Threat': 50,\n",
              " 'Criminal Planning/Confessions, Harassment': 51,\n",
              " 'Hate/Identity Hate, Sexual': 52,\n",
              " 'Controlled/Regulated Substances, Criminal Planning/Confessions, Harassment': 53,\n",
              " 'Guns and Illegal Weapons, Hate/Identity Hate': 54,\n",
              " 'Criminal Planning/Confessions, Sexual (minor)': 55,\n",
              " 'Criminal Planning/Confessions, Harassment, Sexual': 56,\n",
              " 'Criminal Planning/Confessions, Harassment, Sexual, Violence': 57,\n",
              " 'Controlled/Regulated Substances, Guns and Illegal Weapons': 58,\n",
              " 'Criminal Planning/Confessions, Harassment, PII/Privacy': 59,\n",
              " 'Suicide and Self Harm, Violence': 60,\n",
              " 'Harassment, Violence': 61,\n",
              " 'PII/Privacy, Sexual': 62,\n",
              " 'PII/Privacy, Violence': 63,\n",
              " 'Harassment, PII/Privacy, Profanity': 64,\n",
              " 'Harassment, PII/Privacy, Suicide and Self Harm': 65,\n",
              " 'Controlled/Regulated Substances, Harassment': 66,\n",
              " 'Profanity, Threat, Violence': 67,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons, Profanity': 68,\n",
              " 'Sexual, Threat': 69,\n",
              " 'Controlled/Regulated Substances, Profanity': 70,\n",
              " 'Criminal Planning/Confessions, Threat, Violence': 71,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons, Threat': 72,\n",
              " 'Criminal Planning/Confessions, Harassment, Hate/Identity Hate': 73,\n",
              " 'Sexual (minor), Violence': 74,\n",
              " 'Hate/Identity Hate, Profanity, Violence': 75,\n",
              " 'Guns and Illegal Weapons, Threat': 76,\n",
              " 'Controlled/Regulated Substances, Harassment, Hate/Identity Hate, Profanity, Sexual': 77,\n",
              " 'Controlled/Regulated Substances, Violence': 78,\n",
              " 'Criminal Planning/Confessions, Harassment, Profanity': 79,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons, Suicide and Self Harm, Violence': 80,\n",
              " 'Sexual (minor), Threat': 81,\n",
              " 'Sexual, Threat, Violence': 82,\n",
              " 'Criminal Planning/Confessions, Sexual, Threat, Violence': 83,\n",
              " 'Criminal Planning/Confessions, PII/Privacy, Violence': 84,\n",
              " 'Criminal Planning/Confessions, Sexual (minor), Violence': 85,\n",
              " 'Controlled/Regulated Substances, Sexual': 86,\n",
              " 'Harassment, Hate/Identity Hate, Profanity, Suicide and Self Harm, Violence': 87,\n",
              " 'Harassment, Suicide and Self Harm': 88,\n",
              " 'Controlled/Regulated Substances, Sexual (minor)': 89,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons, Profanity, Violence': 90,\n",
              " 'Hate/Identity Hate, Sexual (minor), Violence': 91,\n",
              " 'Guns and Illegal Weapons, PII/Privacy, Violence': 92,\n",
              " 'Criminal Planning/Confessions, Hate/Identity Hate': 93,\n",
              " 'Controlled/Regulated Substances, Criminal Planning/Confessions, Suicide and Self Harm': 94,\n",
              " 'Controlled/Regulated Substances, Criminal Planning/Confessions, Guns and Illegal Weapons, Violence': 95,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons, Hate/Identity Hate, Violence': 96,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons, Suicide and Self Harm': 97,\n",
              " 'Harassment, PII/Privacy, Sexual (minor)': 98,\n",
              " 'Criminal Planning/Confessions, PII/Privacy, Sexual': 99,\n",
              " 'Guns and Illegal Weapons, Profanity': 100,\n",
              " 'Guns and Illegal Weapons, Harassment, Profanity': 101,\n",
              " 'Profanity, Threat': 102,\n",
              " 'PII/Privacy, Profanity': 103,\n",
              " 'Guns and Illegal Weapons, Harassment': 104,\n",
              " 'Profanity, Sexual (minor), Violence': 105,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons, Harassment': 106,\n",
              " 'Controlled/Regulated Substances, Hate/Identity Hate, Violence': 107,\n",
              " 'Hate/Identity Hate, Profanity, Sexual, Violence': 108,\n",
              " 'Controlled/Regulated Substances, PII/Privacy': 109,\n",
              " 'Profanity, Sexual, Violence': 110,\n",
              " 'Criminal Planning/Confessions, Harassment, Violence': 111,\n",
              " 'Criminal Planning/Confessions, Hate/Identity Hate, Sexual': 112,\n",
              " 'Controlled/Regulated Substances, Harassment, Violence': 113,\n",
              " 'Controlled/Regulated Substances, Guns and Illegal Weapons, Hate/Identity Hate, Profanity': 114,\n",
              " 'Harassment, Profanity, Sexual': 115,\n",
              " 'PII/Privacy, Threat, Violence': 116,\n",
              " 'Sexual, Suicide and Self Harm': 117,\n",
              " 'Profanity, Sexual, Sexual (minor)': 118,\n",
              " 'Criminal Planning/Confessions, Profanity, Violence': 119,\n",
              " 'Criminal Planning/Confessions, Hate/Identity Hate, Profanity': 120,\n",
              " 'Hate/Identity Hate, Suicide and Self Harm, Violence': 121,\n",
              " 'Harassment, Threat': 122,\n",
              " 'Harassment, Hate/Identity Hate, Violence': 123,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons, PII/Privacy': 124,\n",
              " 'Controlled/Regulated Substances, Criminal Planning/Confessions, Violence': 125,\n",
              " 'Criminal Planning/Confessions, Guns and Illegal Weapons, Sexual, Violence': 126,\n",
              " 'Hate/Identity Hate, Threat, Violence': 127,\n",
              " 'Profanity, Suicide and Self Harm': 128,\n",
              " 'Criminal Planning/Confessions, Suicide and Self Harm': 129,\n",
              " 'Harassment, Sexual (minor)': 130,\n",
              " 'Controlled/Regulated Substances, Profanity, Sexual': 131,\n",
              " 'Controlled/Regulated Substances, Criminal Planning/Confessions, Profanity': 132,\n",
              " 'Guns and Illegal Weapons, PII/Privacy': 133,\n",
              " 'Hate/Identity Hate, Profanity, Sexual': 134,\n",
              " 'Hate/Identity Hate, Sexual (minor)': 135,\n",
              " 'Criminal Planning/Confessions, Profanity, Sexual': 136,\n",
              " 'Guns and Illegal Weapons, Suicide and Self Harm, Violence': 137,\n",
              " 'Hate/Identity Hate, PII/Privacy': 138,\n",
              " 'Sexual, Suicide and Self Harm, Violence': 139,\n",
              " 'Harassment, Hate/Identity Hate, Suicide and Self Harm': 140,\n",
              " 'Controlled/Regulated Substances, Criminal Planning/Confessions, Sexual, Violence': 141,\n",
              " 'Criminal Planning/Confessions, Profanity, Sexual, Violence': 142,\n",
              " 'Controlled/Regulated Substances, Hate/Identity Hate': 143,\n",
              " 'Harassment, Profanity, Violence': 144,\n",
              " 'Harassment, Threat, Violence': 145}"
            ]


